"use client";

import { useEffect, useState } from "react";
import { api } from "@/lib/api";
import { cn } from "@/lib/utils";
import { avatarGradient, initials } from "@/lib/avatar";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";
import { FileText, Loader2, Printer, Leaf, Activity, Pill, Stethoscope } from "lucide-react";

const THERAPY_ICONS: Record<string, any> = {
  "Ilaj-bil-Dawa": Pill,
  "Ilaj-bil-Ghadha": Leaf,
  "Ilaj-bil-Tadbeer": Activity,
  "Ilaj-bil-Yad": Stethoscope,
};

export function PatientPrescriptionsView() {
  const [prescriptions, setPrescriptions] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    api.get<{ prescriptions: any[] }>("/api/prescriptions")
      .then((r) => setPrescriptions(r.prescriptions || []))
      .catch((e: any) => toast.error(e.message))
      .finally(() => setLoading(false));
  }, []);

  const print = (pr: any) => {
    const win = window.open("", "_blank");
    if (!win) return;
    win.document.write(`
      <html><head><title>Prescription - ${pr.hakim?.name}</title>
      <style>
        body { font-family: Georgia, serif; padding: 40px; max-width: 700px; margin: auto; color: #1a1a1a; }
        h1 { color: #0f766e; margin-bottom: 0; }
        .meta { color: #666; font-size: 14px; margin: 4px 0 24px; }
        h2 { color: #b45309; font-size: 18px; border-bottom: 2px solid #b45309; padding-bottom: 6px; }
        .item { margin: 10px 0; padding: 8px; background: #f6f5f0; border-radius: 6px; }
        .item b { color: #0f766e; }
        .notes { margin-top: 20px; font-style: italic; color: #555; }
        .rx { font-size: 48px; color: #0f766e; }
      </style></head><body>
      <div class="rx">℞</div>
      <h1>The Hekim's Connect</h1>
      <div class="meta">Prescribed by ${pr.hakim?.name} · ${pr.hakim?.specialization}<br/>
      ${new Date(pr.createdAt).toLocaleDateString("en-IN", { dateStyle: "full" })} · Therapy: ${pr.therapyType}</div>
      <h2>Formulation</h2>
      ${pr.items.map((it: any) => `<div class="item"><b>${it.name}</b> — ${it.dose}<br/>${it.frequency} · ${it.instructions}</div>`).join("")}
      ${pr.notes ? `<p class="notes">${pr.notes}</p>` : ""}
      <p style="margin-top:40px;font-size:12px;color:#999;">This prescription is generated by The Hekim's Connect platform. Consult your Hakim before any change in dosage.</p>
      </body></html>`);
    win.document.close();
    win.print();
  };

  if (loading) return <div className="text-center py-12 text-muted-foreground"><Loader2 className="h-5 w-5 animate-spin inline mr-2" /> Loading…</div>;

  return (
    <div className="space-y-5">
      <div>
        <h2 className="font-serif text-xl font-bold">My Prescriptions</h2>
        <p className="text-sm text-muted-foreground">Classical Unani formulations prescribed to you.</p>
      </div>

      {prescriptions.length === 0 ? (
        <Card className="p-10 border-dashed border-border bg-card/60 text-center">
          <FileText className="h-12 w-12 mx-auto text-muted-foreground/40 mb-3" />
          <p className="font-medium">No prescriptions yet</p>
          <p className="text-sm text-muted-foreground">Your Hakim&apos;s formulations will appear here after a consultation.</p>
        </Card>
      ) : (
        <div className="grid sm:grid-cols-2 gap-4">
          {prescriptions.map((pr) => {
            const Icon = THERAPY_ICONS[pr.therapyType] || Pill;
            return (
              <Card key={pr.id} className="p-5 border-border/50 bg-card/60 hover:border-primary/40 transition-colors">
                <div className="flex items-start justify-between mb-3">
                  <div className="flex items-center gap-2.5">
                    <div className={cn("h-10 w-10 rounded-full bg-gradient-to-br flex items-center justify-center text-xs font-semibold text-white", avatarGradient(pr.hakim?.avatarColor))}>
                      {initials(pr.hakim?.name)}
                    </div>
                    <div>
                      <p className="font-medium">{pr.hakim?.name}</p>
                      <p className="text-[11px] text-muted-foreground">{new Date(pr.createdAt).toLocaleDateString()}</p>
                    </div>
                  </div>
                  <Badge variant="outline" className="text-primary border-primary/30 bg-primary/10"><Icon className="h-3 w-3 mr-1" />{pr.therapyType}</Badge>
                </div>
                <div className="space-y-2 mb-3">
                  {pr.items.map((it: any, i: number) => (
                    <div key={i} className="rounded-lg bg-background/40 p-2.5 border border-border/30">
                      <p className="text-sm font-medium text-primary">{it.name}</p>
                      <p className="text-xs text-muted-foreground">{it.dose} · {it.frequency}</p>
                      <p className="text-xs text-muted-foreground italic">{it.instructions}</p>
                    </div>
                  ))}
                </div>
                {pr.notes && <p className="text-xs text-muted-foreground italic border-t border-border/30 pt-2">{pr.notes}</p>}
                <Button size="sm" variant="outline" className="w-full mt-3" onClick={() => print(pr)}>
                  <Printer className="h-3.5 w-3.5 mr-1" /> Print Prescription
                </Button>
              </Card>
            );
          })}
        </div>
      )}
    </div>
  );
}
